USE [SMP]

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Friends')
BEGIN
	CREATE TABLE Friends (
		UserOneId UNIQUEIDENTIFIER NOT NULL,
		UserTwoId UNIQUEIDENTIFIER NOT NULL,
		AcceptedDate DATETIME NOT NULL,
		CONSTRAINT PK_Friends PRIMARY KEY (UserOneId, UserTwoId),
		CONSTRAINT FK_Friends_UserOneId_Users_Id FOREIGN KEY (UserOneId) REFERENCES Users(Id),
		CONSTRAINT FK_Friends_UserTwoId_Users_Id FOREIGN KEY (UserTwoId) REFERENCES Users(Id),
	);
END