IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Users')
BEGIN
	CREATE TABLE Users (
		Id UNIQUEIDENTIFIER NOT NULL,
		Username VARCHAR(32) NOT NULL,
		Password VARCHAR(255) NOT NULL,
		Email VARCHAR(255),
		ProfilePictureUrl VARCHAR(255),
		CONSTRAINT PK_Users PRIMARY KEY (Id)
	);
END