IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Comments')
BEGIN
	CREATE TABLE Comments (
		Id BIGINT NOT NULL,
		Date DATETIME NOT NULL,
		Content VARCHAR(MAX) NOT NULL,
		PostId BIGINT NOT NULL,
		CONSTRAINT PK_Comments PRIMARY KEY (Id),
		CONSTRAINT FK_Comments_PostId_Posts_Id FOREIGN KEY (PostId) REFERENCES Posts(Id)
	);
END