USE [SMP]

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RequestTypes')
BEGIN
	CREATE TABLE RequestTypes (
		Id TINYINT NOT NULL,
		Type VARCHAR(32) NOT NULL,
		CONSTRAINT PK_RequestTypes PRIMARY KEY (Id)
	);
END