IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Requests')
BEGIN
	CREATE TABLE Requests (
		SenderId UNIQUEIDENTIFIER NOT NULL,
		ReceiverId UNIQUEIDENTIFIER NOT NULL,
		SentDate DATETIME NOT NULL,
		RequestTypeId TINYINT NOT NULL,
		CONSTRAINT PK_Requests PRIMARY KEY (SenderId, ReceiverId, RequestTypeId),
		CONSTRAINT FK_Requests_RequestTypeId_RequestTypes_Id FOREIGN KEY (RequestTypeId) REFERENCES RequestTypes(Id)
	);
END