IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Posts')
BEGIN
	CREATE TABLE Posts (
		Id BIGINT IDENTITY(1,1) NOT NULL,
		Date DATETIME NOT NULL,
		Content VARCHAR(MAX) NOT NULL,
		SenderId UNIQUEIDENTIFIER NOT NULL,
		CONSTRAINT PK_Posts PRIMARY KEY (Id),
		CONSTRAINT FK_Posts_SenderId_Users_Id FOREIGN KEY (SenderId) REFERENCES Users(Id)
	);
END