IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'CreatedAt' AND TABLE_SCHEMA = 'DBO')
BEGIN
	ALTER TABLE Users ADD CreatedAt DATETIME NOT NULL;
END