IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ActionTypes')
BEGIN
	CREATE TABLE ActionTypes (
		Id TINYINT IDENTITY(1,1) NOT NULL,
		Type VARCHAR(32) NOT NULL,
		CONSTRAINT PK_ActionTypes PRIMARY KEY (Id)
	);
END