IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Comments' AND COLUMN_NAME = 'PostId' AND TABLE_SCHEMA = 'DBO')
BEGIN
	ALTER TABLE Comments DROP CONSTRAINT FK_Comments_PostId_Posts_Id
	ALTER TABLE Comments DROP COLUMN PostId;
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Posts')
BEGIN
	DROP TABLE Posts;
END