IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Actions')
BEGIN
	CREATE TABLE Actions (
		Id UNIQUEIDENTIFIER NOT NULL,
		UserId UNIQUEIDENTIFIER NOT NULL,
		ActionTypeId TINYINT NOT NULL,
		CreatedAt DATETIME NOT NULL,
		ExpiresAt DATETIME NOT NULL,
		CONSTRAINT PK_Actions PRIMARY KEY (Id),
		CONSTRAINT FK_Actions_UserId_Users_Id FOREIGN KEY (UserId) REFERENCES Users(Id),
		CONSTRAINT FK_Actions_ActionTypeId_ActionTypes_Id FOREIGN KEY (ActionTypeId) REFERENCES ActionTypes(Id)
	);
END