name: Angular - Build WebApp

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run npm install and ng build
      run: |
        cd src/Smp.Web/ClientApp
        npm install --exact-versions
        npm install -g @angular/cli
        ng build
