name: Angular - Build WebApp

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      directory: ./src/Smp.Web/ClientApp

    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: |
        sudo npm install --exact-versions
        sudo npm install -g @angular/cli
      working-directory: ${{env.directory}}
    - name:  ng build
      run: sudo ng build
      working-directory: ${{env.directory}}
    - name: ng test
      run: sudo npm run test -- --configuration=headless
      working-directory: ${{env.directory}}
